version: '1' 
services:
  db:
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '32000:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-net
  api:
    build: .
    ports:
     - "5001:5001"
    volumes:
     - .:/app
    depends_on:
      db:
        condition: service_completed_successfully
    networks:
      - db-net

networks:
  db-net:
    driver: bridge
